/* config.h. Generated by cmake from config.h.cmake */

#ifndef TAGLIB_CONFIG_H
#define TAGLIB_CONFIG_H

/* Defined if your compiler supports some byte swap functions */
/* #undef HAVE_GCC_BYTESWAP */
/* #undef HAVE_GLIBC_BYTESWAP */
#define   HAVE_MSC_BYTESWAP 1
/* #undef HAVE_MAC_BYTESWAP */
/* #undef HAVE_OPENBSD_BYTESWAP */

/* Defined if your compiler supports ISO _strdup */
#define   HAVE_ISO_STRDUP 1

/* Defined if zlib is installed */
/* #undef HAVE_ZLIB */

/* Indicates whether debug messages are shown even in release mode */
/* #undef TRACE_IN_RELEASE */

#define TESTS_DIR "E:/Tarek/Collage/Second Year/First Semester/OOP/Assignments/Assignment 2 AhmedVerison/juce_audio_edit/Source/taglib-2.1.1/tests/"
/* #undef TESTS_TMPDIR */

#endif
